post http://192.168.10.218:8080/twinx-api/api/v1/users/login
Content-Type: application/json

{
    "loginId" : "dhhan",
    "password" : "1234"
}

###
put http://192.168.10.218:8080/twinx-api/api/v1/users/change-password
Content-Type: application/json

{
    "userLoginId" : "dhhan",
    "newPassword" : "1111"
}


### SSE livecheck
http://192.168.10.218:3001/test/livecheck

### SSE 
http://192.168.10.218:3001/test/stream
Content-Type: text/event-stream;charset=UTF-8
transfer-encoding: chunked
